### ISSUE TITLE
No dev scripts/instructions

### ISSUE THREAD

**Issue by jonorthwash** [sapradhan/ne-trad-ttf#2]
There are no scripts or instructions for compiling source to installer.

**Comment by sapradhan** [comment]
For windows - use [Microsoft Keyboard Layout Creator](https://www.microsoft.com/en-us/download/details.aspx?id=102134) to build klc source to executable 

For linux - it is a m17n layout which does not need any compiling, just drop it where your m17n layouts reside. 

updated README.md
